#!/usr/bin/php
<?php
require('config.php');

$packet = file_get_contents(ES_INSTANCE.'/_aliases');
$data = json_decode($packet,true);
ksort($data);

foreach($data as $index => $index_params) {
  echo 'Found index '.$index.' : ';
  preg_match('/([a-z-_]+)\-([0-9]{4})\.([0-9]{2})\.([0-9]{2})/',$index,$matches);
  if(count($matches) < 4) {
    echo ' Not logstash, skipping'.PHP_EOL;
    continue;
  }
  list($full,$index,$year,$month,$day) = $matches;
  
  $time = strtotime(implode('-',array($year,$month,$day)));
  
  //if(true) {
  if((time() - $time) > 60*60*24*(DAY_TO_KEEP+1)) {
    echo 'Older than '.DAY_TO_KEEP.' days, deleting ... ';
    $url = ES_INSTANCE.'/'.$full;
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL,$url);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");
    $result = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    echo $httpCode.PHP_EOL;
    curl_close($ch); 
  } else {
    echo 'Keeping'.PHP_EOL;
  }
}

